name: Deploy to GitHub Pages

on:
  push:
    branches:
      - feat/adjust-backend-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Instalación de dependencias
        run: npm install

      - name: Build del proyecto
        run: npm run build

      - name: Despliegue a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true